project_name = "job-tracker"
environment  = "dev"
aws_region   = "us-east-1"
vpc_cidr             = "10.0.0.0/16"
public_subnet_cidrs  = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs = ["10.0.3.0/24", "10.0.4.0/24"]
availability_zones   = ["us-east-1a", "us-east-1b"]
app_instance_type = "t3.micro"
key_pair_name     = "devops-key"
db_name           = "jobtracker"
db_username       = "dbadmin"
db_password       = "Change_Me_123!"
db_instance_class = "db.t3.micro"
allowed_ssh_cidr = "0.0.0.0/0"
